-- Existing task rows are kept while the public table moves to the singular name and numeric ID.
alter table tasks rename to task;
alter table task add column task_id bigint generated by default as identity;
update task set task_id = default where task_id is null;
alter table task alter column task_id set not null;
alter table task drop constraint tasks_pkey;
alter table task drop column id;
alter table task rename column task_id to id;
alter table task add constraint task_pkey primary key (id);
alter index tasks_due_date_idx rename to task_due_date_idx;
