-- Normalize legacy primary keys to numeric IDs while preserving legacy values.
create function migrate_to_numeric_id(target_table regclass) returns void language plpgsql as $$
declare primary_constraint text;
begin
    select conname into primary_constraint from pg_constraint where conrelid = target_table and contype = 'p';
    execute format('alter table %s rename column id to legacy_key', target_table);
    execute format('alter table %s add column id bigint generated by default as identity', target_table);
    execute format('update %s set id = default where id is null', target_table);
    execute format('alter table %s alter column id set not null', target_table);
    execute format('alter table %s drop constraint %I', target_table, primary_constraint);
    execute format('alter table %s add constraint %I primary key (id)', target_table, replace(target_table::text, '.', '_') || '_pkey');
    execute format('alter table %s add constraint %I unique (legacy_key)', target_table, replace(target_table::text, '.', '_') || '_legacy_key_key');
end;
$$;

-- app_document keeps document_key as its business key, but gets a numeric internal key.
alter table app_document add column id bigint generated by default as identity;
update app_document set id = default where id is null;
alter table app_document alter column id set not null;
alter table app_document drop constraint app_documents_pkey;
alter table app_document add constraint app_document_pkey primary key (id);
alter table app_document add constraint app_document_document_key_key unique (document_key);

-- Drop legacy foreign keys before the referenced text/UUID keys change.
alter table automation_posting_record drop constraint automation_posting_history_content_id_fkey;
alter table content_output drop constraint content_outputs_package_id_fkey;

select migrate_to_numeric_id('automation_content');
select migrate_to_numeric_id('automation_posting_record');
select migrate_to_numeric_id('dashboard_kpi');
select migrate_to_numeric_id('approval');
select migrate_to_numeric_id('automation_run');
select migrate_to_numeric_id('ai_news_item');
select migrate_to_numeric_id('ai_news_briefing');
select migrate_to_numeric_id('ai_operation_run');
select migrate_to_numeric_id('content_package');

-- Restore numeric foreign-key relationships using the preserved legacy keys.
alter table automation_posting_record rename column content_id to content_legacy_key;
alter table automation_posting_record add column content_id bigint;
update automation_posting_record record set content_id = content.id from automation_content content where content.legacy_key = record.content_legacy_key;
alter table automation_posting_record alter column content_id set not null;
alter table automation_posting_record add constraint automation_posting_record_content_id_fkey foreign key (content_id) references automation_content(id);

alter table content_output rename column package_id to package_legacy_key;
alter table content_output add column package_id bigint;
update content_output output set package_id = package.id from content_package package where package.legacy_key = output.package_legacy_key;
alter table content_output alter column package_id set not null;
alter table content_output add constraint content_output_package_id_fkey foreign key (package_id) references content_package(id) on delete restrict;

drop function migrate_to_numeric_id(regclass);

-- A deletion never removes a row. Domain-specific status columns remain independent.
alter table app_document add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table app_document add column removed_at timestamptz;
alter table automation_keyword add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table automation_keyword add column removed_at timestamptz;
alter table automation_content add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table automation_content add column removed_at timestamptz;
alter table automation_posting_record add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table automation_posting_record add column removed_at timestamptz;
alter table task add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table task add column removed_at timestamptz;
alter table dashboard_kpi add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table dashboard_kpi add column removed_at timestamptz;
alter table approval add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table approval add column removed_at timestamptz;
alter table automation_run add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table automation_run add column removed_at timestamptz;
alter table ai_news_item add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table ai_news_item add column removed_at timestamptz;
alter table ai_news_briefing add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table ai_news_briefing add column removed_at timestamptz;
alter table ai_operation_run add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table ai_operation_run add column removed_at timestamptz;
alter table content_package add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table content_package add column removed_at timestamptz;
alter table content_output add column lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed'));
alter table content_output add column removed_at timestamptz;
