-- 인스타툰 컷 이미지. 바이트는 app_document(jsonb)에 넣지 않는다.
-- JsonDocumentStore 는 문서 전체를 매번 재직렬화하고 통째로 읽어, 목록 조회마다 수백 MB를 읽게 된다.
-- 컷별 진행 상태도 여기 둔다. 문서에 두면 컷 하나 끝날 때마다 툰 20개 목록을 다시 쓰고,
-- 대본 생성 요청과 겹치면 마지막 쓰기가 이겨 진행 상태가 사라진다.
create table toon_image (
    id bigint generated by default as identity primary key,
    toon_id text not null,
    panel_number integer not null,
    -- 데모 격리. JsonDocumentStore 의 demo: 접두와 같은 단위(데모 전체가 한 공간)로 맞춘다.
    owner text not null default 'owner' check (owner in ('owner', 'demo')),
    status text not null default '생성중' check (status in ('생성중', '완료', '실패')),
    mime_type text,
    image_bytes bytea,
    error text,
    requested_at timestamptz not null default now(),
    completed_at timestamptz,
    lifecycle_state text not null default 'active' check (lifecycle_state in ('active', 'removed')),
    removed_at timestamptz
);

-- 같은 툰의 같은 컷은 한 행. 재시도가 새 행을 만들지 않고 그 행을 되돌린다.
create unique index toon_image_panel_key on toon_image (toon_id, panel_number);
create index toon_image_toon_idx on toon_image (toon_id, owner);
