spring:
  application:
    name: office-dashboard
  config:
    import: optional:file:config/dashboard.properties
  web:
    resources:
      static-locations: file:frontend/static/

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${PORT:8765}
